---
- name: pull flamethrower docker image
  docker_image:
    name: "{{ flamethrower_image }}:{{ flamethrower_version }}"
    source: pull

- name: create individual flames
  template:
    src: flame@.service
    dest: /etc/systemd/system/flame@{{ item.temperature }}.service
  with_items:
    - temperature: hot
      max_qps: 50
    - temperature: warm
      max_qps: 50

- name: start and enable flames
  systemd:
    name: "flame@{{ item }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - hot
    - warm
