---
- hosts: all
  become: true
  tasks:
    - name: "install ansible deps"
      raw: apt-get install python-minimal python-apt aptitude -y

- hosts: all
  become: true
  vars:
    server_cert: /etc/letsencrypt/dns.dns-tls.com.pem
    server_key: /etc/letsencrypt/dns.dns-tls.com.key
  roles:
    - knot-resolver
